// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: proto/notifierDefine/notifier.proto

package notifierDefine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomNumber uint32 `protobuf:"varint,1,opt,name=roomNumber,proto3" json:"roomNumber,omitempty"`
	Flag       uint32 `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *NotifierRequest) Reset() {
	*x = NotifierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notifierDefine_notifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifierRequest) ProtoMessage() {}

func (x *NotifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifierDefine_notifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifierRequest.ProtoReflect.Descriptor instead.
func (*NotifierRequest) Descriptor() ([]byte, []int) {
	return file_proto_notifierDefine_notifier_proto_rawDescGZIP(), []int{0}
}

func (x *NotifierRequest) GetRoomNumber() uint32 {
	if x != nil {
		return x.RoomNumber
	}
	return 0
}

func (x *NotifierRequest) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type NotifierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *NotifierResponse) Reset() {
	*x = NotifierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_notifierDefine_notifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifierResponse) ProtoMessage() {}

func (x *NotifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notifierDefine_notifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifierResponse.ProtoReflect.Descriptor instead.
func (*NotifierResponse) Descriptor() ([]byte, []int) {
	return file_proto_notifierDefine_notifier_proto_rawDescGZIP(), []int{1}
}

func (x *NotifierResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_notifierDefine_notifier_proto protoreflect.FileDescriptor

var file_proto_notifierDefine_notifier_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x65, 0x22, 0x45, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x6f,
	0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x2c, 0x0a, 0x10,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x62, 0x0a, 0x0f, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a,
	0x08, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x18,
	0x5a, 0x16, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_notifierDefine_notifier_proto_rawDescOnce sync.Once
	file_proto_notifierDefine_notifier_proto_rawDescData = file_proto_notifierDefine_notifier_proto_rawDesc
)

func file_proto_notifierDefine_notifier_proto_rawDescGZIP() []byte {
	file_proto_notifierDefine_notifier_proto_rawDescOnce.Do(func() {
		file_proto_notifierDefine_notifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_notifierDefine_notifier_proto_rawDescData)
	})
	return file_proto_notifierDefine_notifier_proto_rawDescData
}

var file_proto_notifierDefine_notifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_notifierDefine_notifier_proto_goTypes = []interface{}{
	(*NotifierRequest)(nil),  // 0: notifierDefine.NotifierRequest
	(*NotifierResponse)(nil), // 1: notifierDefine.NotifierResponse
}
var file_proto_notifierDefine_notifier_proto_depIdxs = []int32{
	0, // 0: notifierDefine.NotifierService.Notifier:input_type -> notifierDefine.NotifierRequest
	1, // 1: notifierDefine.NotifierService.Notifier:output_type -> notifierDefine.NotifierResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_notifierDefine_notifier_proto_init() }
func file_proto_notifierDefine_notifier_proto_init() {
	if File_proto_notifierDefine_notifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_notifierDefine_notifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_notifierDefine_notifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_notifierDefine_notifier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notifierDefine_notifier_proto_goTypes,
		DependencyIndexes: file_proto_notifierDefine_notifier_proto_depIdxs,
		MessageInfos:      file_proto_notifierDefine_notifier_proto_msgTypes,
	}.Build()
	File_proto_notifierDefine_notifier_proto = out.File
	file_proto_notifierDefine_notifier_proto_rawDesc = nil
	file_proto_notifierDefine_notifier_proto_goTypes = nil
	file_proto_notifierDefine_notifier_proto_depIdxs = nil
}
