-- MySQL Script generated by MySQL Workbench
-- Tue Oct 26 23:40:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notifier
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notifier
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notifier` DEFAULT CHARACTER SET utf8 ;
USE `notifier` ;

-- -----------------------------------------------------
-- Table `notifier`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notifier`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apartment` VARCHAR(256) NOT NULL,
  `room` INT NOT NULL,
  `state` TINYINT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `apartment_UNIQUE` (`apartment` ASC) VISIBLE,
  UNIQUE INDEX `room_UNIQUE` (`room` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
