version: "3.8"

services:
  db:
    image: mysql:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:53306:3306"
    environment:
      - MYSQL_DATABASE=notifier
      - MYSQL_USER=notifier
      - MYSQL_PASSWORD=not1f1er0000
      - MYSQL_ROOT_PASSWORD=r00t-not1f1er

  notifier:
    build:
      context: .
      dockerfile: Dockerfile
      target: notifier
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - MYSQL_URL=notifier:not1f1er0000@tcp(db:3306)/notifier?parseTime=true
      - HOST_URL=:8080
    tty: true
    depends_on:
      - db
    working_dir: /go/src
    command: sh launch.sh
