version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "127.0.0.1:53306:3306"
    environment:
      - MYSQL_DATABASE=notifier
      - MYSQL_USER=notifier
      - MYSQL_PASSWORD=not1f1er0000
      - MYSQL_ROOT_PASSWORD=r00t-not1f1er
